### ISSUE TITLE
Christmas/New Year presents this year?

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [headcrab-garage/OpenGoldSrc#86]
???

**Comment by Sh1ft0x0EF** [comment]
I'll try to rush and to do my best to finally make it at least buildable, runnable and maybe even halfway playable by the end of this year
There is still lot of work to do but many things could be done after the engine finally be in usable state

**Comment by SourcePowered** [comment]
Merry Christmas! @Sh1ft0x0EF And Happy new year for 2018!
Please try to prepare a normally compiled version, many of my friends are looking forward to this engine (they're not going to use GitHub because they're all map developers or model makers). They can't programming code or build a compiler environment. So, please make a possible version of it as soon as possible. Even if it's very, very alpha or beta.

**Comment by Sh1ft0x0EF** [comment]
@SourcePowered 
Hey! Thanks! Happy New Year to you too!
Thanks for such a long waiting
It's really been a while
I will try my best to finally make this engine buildable
